//Item Hides
onEvent('jei.hide.items', event => {
  event.hide('jobsplus:small_backpack')
  event.hide('jobsplus:medium_backpack')
  event.hide('jobsplus:large_backpack')
  event.hide('jobsplus:huge_backpack')
  event.hide('jobsplus:ender_backpack')
  event.hide('minecraft:wooden_pickaxe')
  event.hide('minecraft:stone_pickaxe')
  event.hide('minecraft:wooden_sword')
  event.hide('minecraft:stone_sword')
  event.hide('minecraft:wooden_shovel')
  event.hide('minecraft:stone_shovel')
  event.hide('minecraft:wooden:hoe')
  event.hide('minecraft:stone:hoe')
  event.hide('minecraft:wooden_axe')
  event.hide('minecraft:stone_axe')
  event.hide('ringsofascension:ring_flight')
})